# ~/.pal/config/99_user_costmap.yaml

local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    rolling_window: true
    width: 6
    height: 6
    resolution: 0.05
    footprint: "[[0.35, 0.24], [-0.35, 0.24], [-0.35, -0.24], [0.35, -0.24]]"
    footprint_padding: 0.1
    update_frequency: 10.0
    publish_frequency: 10.0
    always_send_full_costmap: true
    track_unknown_space: false
    use_sim_time: true
    
    plugins: ["obstacle_laser_layer", "inflation_layer"]

    obstacle_laser_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: "scan social_points"
      footprint_clearing_enabled: true
      
      scan:
        topic: "/scan"
        expected_update_rate: 1.0
        max_obstacle_height: 2.0
        clearing: true
        marking: true
        data_type: "LaserScan"
        inf_is_valid: true
        observation_persistence: 0.0
        raytrace_max_range: 6.0
        raytrace_min_range: 0.0
        obstacle_max_range: 5.5
        obstacle_min_range: 0.0

      social_points:
        topic: "/social_obstacles"
        data_type: "PointCloud2"
        clearing: false            # social obstacles should not clear others
        marking: true              # they mark cells as obstacles
        max_obstacle_height: 2.0
        min_obstacle_height: 0.0
        obstacle_max_range: 10.0
        raytrace_max_range: 0.0    # no raytracing for social
        observation_persistence: 0.0
        expected_update_rate: 0.5
        inf_is_valid: false

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 2.5
      inflation_radius: 0.75


global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    resolution: 0.05
    footprint_padding: 0.09
    update_frequency: 5.0
    publish_frequency: 0.5
    always_send_full_costmap: true
    track_unknown_space: true
    use_sim_time: true
    
    plugins: ["static_layer", "obstacle_laser_layer", "inflation_layer"]

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      subscribe_to_updates: true
      map_subscribe_transient_local: true

    obstacle_laser_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      combination_method: 0
      observation_sources: "scan"  # No social_points - humans only in local costmap
      footprint_clearing_enabled: true
      
      scan:
        topic: "/scan"
        expected_update_rate: 1.0
        max_obstacle_height: 2.0
        clearing: true
        marking: true
        data_type: "LaserScan"
        inf_is_valid: false
        observation_persistence: 2.0
        raytrace_max_range: 15.0
        raytrace_min_range: 0.0
        obstacle_max_range: 14.0
        obstacle_min_range: 0.0
        
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 2.5
      inflation_radius: 0.75
