# User override for bt_navigator configuration
# This file points to custom behavior trees for navigation

bt_navigator:
  ros__parameters:
    # Point to our custom behavior tree (installed via colcon build)
    default_nav_to_pose_bt_xml: /home/user/install/tiago_social_sim/share/tiago_social_sim/behavior_trees/custom_navigate_to_pose.xml
    
    # Slow down BT tick rate (default is 10ms, this is 20ms)
    bt_loop_duration: 20
